---
title: "graphs_datafest"
output: html_document
date: "2024-04-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r}
# loading all datasets
page_views <- read.csv("page_views.csv")
new_page_views <- page_views %>%
  filter(book == 'College / Statistics and Data Science (ABC)') %>%
  group_by(chapter_number)%>%
  summarize(mean_engagement= mean(engaged,na.rm=TRUE))

eoc <- read.csv("checkpoints_eoc.csv")
new_eoc <- eoc %>%
  filter(book == 'College / Statistics and Data Science (ABC)') %>%
  mutate(score=(n_correct/n_possible))%>%
  group_by(chapter_number)%>%
  summarize(mean_score = mean(score,na.rm=TRUE))

media <- read.csv('media_views.csv')
new_media <- media %>%
  filter(book == "College / Statistics and Data Science (ABC)") %>%
  group_by(chapter_number) %>%
  summarize(mean_prop = mean(proportion_video,na.rm=TRUE))

responses <- read.csv("responses.csv")
# finding # of unique questions in chapter and then finding the amount of code questions in that chapter
# from that, finding proportion of code questions and comparing that to learnosity questions
responses.final <- responses %>%
  filter(book == "College / Statistics and Data Science (ABC)", chapter_number <= 12, student_id == "fb7c9a8b-7b0c-4907-90c1-3a6e5230b486") %>%
  group_by(chapter_number) %>%
  select(item_id, item_type) %>%
  distinct()%>%
  mutate(total_questions = n_distinct(item_id),  # Total number of unique questions in the chapter
         code_count = sum(item_type == "code"))%>%
  mutate(prop_code = code_count / total_questions)%>%
  select(chapter_number, total_questions, code_count, prop_code)

resp.final <- unique(responses.final)
```


# engagement level graphs between different chapters
```{r}
library(treemap)
treemap(new_page_views,
        index = c("chapter_number"),
        vSize = "mean_engagement",
        title = "Total Engagement by Chapter",
        fontsize.labels = 10)



ggplot(new_page_views, aes(x = chapter_number, y = mean_engagement)) +
  geom_point(shape = 21, fill = "orange", color = "black", size = 4, alpha = 0.8) +
  geom_smooth(method = "loess", se = FALSE, color = "blue", size = 1.2) +
  labs(x = 'Chapter Number', y = 'Average Engagement') +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    text = element_text(family = "Arial", color = "black", size = 12)
  )


```

# best and worst performances based on chapters
```{r}
ggplot(new_eoc, aes(x = chapter_number, y = mean_score)) +
  geom_point(shape = 21, fill = "lightpink", color = "black", size = 4, alpha = 0.8) +
  geom_smooth(method = "loess", se = FALSE, color = "lightgreen", size = 1.2) +
  labs(x = 'Chapter Number', y = 'Average Score') +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    text = element_text(family = "Arial", color = "black", size = 12)
  )
```


```{r}
ggplot(resp.final, aes(x = chapter_number, y = prop_code)) +
  geom_point(shape = 21, fill = "lightblue", color = "black", size = 4, alpha = 0.8) +
  geom_smooth(method = "loess", se = FALSE, color = "gray", size = 1.2) +
  labs(x = 'Chapter Number', y = 'Proportion of Code Questions') +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    text = element_text(family = "Arial", color = "black", size = 12)
  )
```

# eoc score and prop of code
```{r}
combined <- merge(resp.final,new_eoc)
ggplot(combined, aes(x = prop_code, y = mean_score)) +
  geom_point(shape = 21, fill = "purple", color = "black", size = 4, alpha = 0.8) +
  geom_smooth(method = "loess", se = FALSE, color = "gray", size = 1.2) +
  labs(x = 'Proportion of Coding Questions', y = 'Mean Exam Score') +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    text = element_text(family = "Arial", color = "black", size = 12)
  )

cor(combined$prop_code,combined$mean_score)
```


# eoc score to learnocity
```{r}
combined$prop_learnocity <- (1- combined$prop_code)
ggplot(combined, aes(x = prop_learnocity, y = mean_score)) +
  geom_point(shape = 21, fill = "purple", color = "black", size = 4, alpha = 0.8) +
  geom_smooth(method = "loess", se = FALSE, color = "gray", size = 1.2) +
  labs(x = 'Proportion of Learnocity Questions', y = 'Mean Exam Score') +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    text = element_text(family = "Arial", color = "black", size = 12)
  )

cor(combined$prop_code,combined$mean_score)
```






